source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DataProvider_Example', :exclusive => true do
  pod "DataProvider", :path => "../"
end

target 'DataProvider_Tests', :exclusive => true do
  pod "DataProvider", :path => "../"

  
end
