source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DataProvider_Example' do
  pod "DataProvider", :path => "../"
end

target 'DataProvider_Tests' do
  pod "DataProvider", :path => "../"

  
end
